export const GET_NOTES_ARRAY = 'GET_NOTES_ARRAY';
export const GET_NOTES_EMPTY = 'GET_NOTES_EMPTY';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';
export const GET_NOTES_CLEAR = 'GET_NOTES_CLEAR';

export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';
export const CREATE_NOTE_CLEAR = 'CREATE_NOTE_CLEAR';

export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';
export const DELETE_NOTE_CLEAR = 'DELETE_NOTE_CLEAR';

export const SHOW_NOTE_SUCCESS = 'SHOW_NOTE_SUCCESS';
export const SHOW_NOTE_FAILURE = 'SHOW_NOTE_FAILURE';
export const SHOW_NOTE_CLEAR = 'SHOW_NOTE_CLEAR';

export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAILURE = 'EDIT_NOTE_FAILURE';
export const EDIT_NOTE_CLEAR = 'EDIT_NOTE_CLEAR';

export const DELETE_ALL_NOTES_SUCCESS = 'DELETE_ALL_NOTES_SUCCESS';
export const DELETE_ALL_NOTES_FAILURE = 'DELETE_ALL_NOTES_FAILURE';
export const DELETE_ALL_NOTES_CLEAR = 'DELETE_ALL_NOTES_CLEAR';